import { DecisionForm } from "@/components/DecisionForm";

export default function DecisionSubmitPage() {
  return (
    <main className="shell">
      <section className="hero">
        <span className="eyebrow">Live enforced lane</span>
        <h1>Submit a signal decision.</h1>
        <p>
          This page sends a real decision payload through the live core boundary and renders the
          exact success or validation-failure truth that comes back. Trace and correlation IDs are
          generated by default and surfaced explicitly.
        </p>
      </section>

      <DecisionForm />
    </main>
  );
}
